<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Packages\ExTween\ExTween.csproj" />
      <ProjectReference Include="..\Packages\SecretPlanCore\SecretPlanCore.csproj" />
      <ProjectReference Include="..\Packages\SecretPlanGodot\SecretPlanGodot.csproj" />
      <ProjectReference Include="..\SokoCore\SokoCore.csproj" />
    </ItemGroup>

</Project>
