using System.Runtime.CompilerServices;
using System.Text;
using SecretPlanCore.Core;

namespace SecretPlanCore.Configuration;

/// <summary>
///     Only enum-backable types (int, uint, long, etc.) are valid uses of T, other types will not generate valid source
///     code
/// </summary>
public class GeneratedEnum<TInt> where TInt : unmanaged
{
    private readonly List<Entry> _entries = new();
    private readonly List<Action<StringBuilder>> _extensionMethodGenerators = new();

    public GeneratedEnum(string enumTypeName)
    {
        EnumTypeName = enumTypeName;
    }

    /// <summary>
    ///     Type of the int-like thing that backs this enum
    /// </summary>
    public Type BackingIntType => typeof(TInt);

    public string EnumTypeName { get; }

    public void AddEntry(string name, TInt value, string? comment = null)
    {
        _entries.Add(new Entry(name, value, comment));
    }

    public string GenerateFileName()
    {
        return $"{EnumTypeName}.cs";
    }

    public void AddExtensionMethod(Action<StringBuilder> code)
    {
        _extensionMethodGenerators.Add(code);
    }

    public static string GenerateSourceCodeHeader()
    {
        var builder = new StringBuilder();
        builder.AppendLine(
            $"// Generated by {NameOfCurrentFile().Replace(Environment.CurrentDirectory, "").Replace("\\", "/")}");
        builder.AppendLine("// ReSharper disable IdentifierTypo");
        builder.AppendLine("// ReSharper disable InconsistentNaming");
        builder.AppendLine("// ReSharper disable RedundantNameQualifier");
        builder.AppendLine();
        builder.AppendLine("namespace SecretPlan.Generated;");
        builder.AppendLine();
        return builder.ToString();
    }

    public string GenerateSourceCodeBody()
    {
        _entries.Sort((a, b) => string.Compare(a.EnumValueName, b.EnumValueName, StringComparison.Ordinal));
        var valueType = BackingIntType.FullName;

        var builder = new StringBuilder();
        builder.AppendLine($"public enum {EnumTypeName} : {valueType}");
        builder.AppendLine("{");

        foreach (var entry in _entries)
        {
            if (entry.Comment != null)
            {
                builder.AppendLine();
                builder.AppendLine("    /// <summary>");

                foreach (var line in entry.Comment.SplitLines())
                {
                    builder.AppendLine($"    /// {line}");
                }

                builder.AppendLine("    /// </summary>");
            }

            builder.AppendLine($"    {entry.EnumValueName} = {entry.Value},");
        }

        builder.AppendLine("}");

        if (_extensionMethodGenerators.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine($"public static class {EnumTypeName}Extensions");
            builder.AppendLine("{");

            foreach (var extensionMethod in _extensionMethodGenerators)
            {
                builder.AppendLine();
                extensionMethod(builder);
            }

            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static string NameOfCurrentFile([CallerFilePath] string sourceFilePath = "")
    {
        return sourceFilePath;
    }

    private record Entry(string EnumValueName, TInt Value, string? Comment);
}